classdef Canonical < otp.quasigeostrophic.QuasiGeostrophicProblem
    methods
        function obj = Canonical(varargin)
            tspan = [0, 100];
            params = otp.quasigeostrophic.QuasiGeostrophicParameters( ...
                'Nx', 255, ...
                'Ny', 511, ...
                'ReynoldsNumber', 450, ...
                'RossbyNumber', 0.0036, ...
                'ADLambda', 1, ...
                'ADPasses', 4, ...
                varargin{:});
            psi0 = zeros(params.Nx * params.Ny, 1);
            obj = obj@otp.quasigeostrophic.QuasiGeostrophicProblem(tspan, psi0, params);
        end
    end
end
