classdef FourBody3D < otp.nbody.NBodyProblem
    methods
        function obj = FourBody3D()
            positions = [ ...
                0; 0; 0; ...
                4; 3; 1; ...
                3; -4; -2; ...
                -3; 4; 5];
            velocities = zeros(12, 1);
            y0 = [positions; velocities];
            tspan = [0, 15];
            params = otp.nbody.NBodyParameters( ...
                'SpatialDim', otp.utils.PhysicalConstants.ThreeD, ...
                'Masses', [8; 10; 12; 14], ...
                'GravitationalConstant', 1, ...
                'SofteningLength', 0);
            obj = obj@otp.nbody.NBodyProblem(tspan, y0, params);
        end
    end
end
