disp('Packaging toolbox');
matlab.addons.toolbox.packageToolbox('ODE Test Problems.prj', 'ODE Test Problems.mltbx');
disp('Toolbox packaged');

disp('Installing toolbox');
matlab.addons.toolbox.installToolbox('ODE Test Problems.mltbx');
disp('Toolbox installed');
disp('');
disp('If you are going to be using the test problems in your research, please cite:');
disp('@article{DBLP:journals/corr/abs-1901-04098,');
disp('  author    = {Steven Roberts and');
disp('               Andrey A. Popov and');
disp('               Adrian Sandu},');
disp('  title     = {{ODE} Test Problems: a {MATLAB} suite of initial value problems},');
disp('  journal   = {CoRR},');
disp('  volume    = {abs/1901.04098},');
disp('  year      = {2019},');
disp('  url       = {http://arxiv.org/abs/1901.04098},');
disp('  archivePrefix = {arXiv},');
disp('  eprint    = {1901.04098},');
disp('  timestamp = {Fri, 01 Feb 2019 13:39:59 +0100},');
disp('  biburl    = {https://dblp.org/rec/bib/journals/corr/abs-1901-04098},');
disp('  bibsource = {dblp computer science bibliography, https://dblp.org}');
disp('}');