classdef Canonical < otp.lienard.LienardProblem
    methods
        function obj = Canonical(varargin)
            % Harmonic oscillator
            tspan = [0, 10];
            y0 = [1; 0];
            zeroFun = @(x) 0;
            params = otp.lienard.LienardParameters( ...
                'F', zeroFun, ...
                'DF', zeroFun, ...
                'G', @(x) x, ...
                'DG', @(x) 1, ...
                'P', zeroFun, ...
                'DP', zeroFun, ...
                varargin{:});
            obj = obj@otp.lienard.LienardProblem(tspan, y0, params);            
        end
    end
end
