classdef Canonical < otp.zlakinetics.ZLAKineticsProblem 
    % Canonical preset for the ZLA kinetics problem as descrobe in :cite:p:`Sto98` (pg. 118)
    % where the initial conditions are $y_0 = [0.444, 0.00123, 0, 0.007, 0, 0]^T$ is also
    % provided. The time span is $[0, 180]$.

    methods
        function obj = Canonical(varargin)
            tspan = [0, 180];
            params = otp.zlakinetics.ZLAKineticsParameters( ...
                'k', [18.7, 0.58, 0.09, 0.42], ...
                'K', 34.4, ...
                'KlA', 3.3, ...
                'Ks', 115.83, ...
                'PCO2', 0.9, ...
                'H', 737, ...
                varargin{:});            
            y0 = [0.444; 0.00123; 0; 0.007; 0; 0];
            y0(end) = params.Ks * y0(1) * y0(4);
            
            obj = obj@otp.zlakinetics.ZLAKineticsProblem(tspan, y0, params);
        end
    end
end
