function Jac = jacobian(~, y, A, B, C, M)

Jac = [ ...
    -A - B * y(3), 0, -B * y(1), 0; ...
    A, -M * C * y(3), -M * C * y(2), 0; ...
    A - B * y(3), -M * C * y(3), -B * y(1) - M * C * y(2), C; ...
    B * y(3), 0, B * y(1), -C];

end

