function Jvp = jacobianVectorProduct(~, y, v, sigma, rho, beta)

Jvp = [...
    sigma*(v(2, :) - v(1, :)); ...
    (rho - y(3, :)).*v(1, :) - v(2, :) - y(1, :).*v(3, :); ...
    y(2, :).*v(1, :) + y(1, :).*v(2, :) - beta*v(3, :)];

end
