function j = jacobianStiff(~, u, epsilon, L)

n = size(u, 1)/3;

y = u(1:n);
a = u((n + 1):(2*n));

sparseZeros = sparse(n, n);

j = [spdiags(-(3*y.^2 + a)/epsilon, 0, n, n) + L, ...
    spdiags(-y/epsilon, 0, n, n), ...
    -speye(n)/epsilon; ...
    sparseZeros, ...
    L, ...
    sparseZeros; ...
    sparseZeros, ...
    sparseZeros, ...
    L];

end
