name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  octave:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Octave
        run: |
          sudo apt-get update
          sudo apt-get install -y octave
      - name: Run OTP tests
        run: octave --eval "addpath(genpath('.')); runalltests"
